### ISSUE TITLE
Is it possible to use timestamp column in the Values tab ?

### ISSUE THREAD

**Issue by R-e-M** [BT-OpenSource/bt-grafana-status-dot#10]
Hello,

The mathjs system is very useful compared to others status panels, but as far as I've tried, I can only make computation on the data I've querried, not on the associated timestamp. Is there any way to do this ? (to go further, my final goal would be to compute the duration since the last measurement).

Thanks !

**Comment by R-e-M** [comment]
Thank you for your response !

But I finally end up to write a little flask python proxy to do what I
wanted, and I can now use all python environment to perform my
post-processing.

Thank you anyway and good luck for your project :)

Le mar. 29 janv. 2019 à 12:28, Jonas Bleyl <notifications@github.com> a
écrit :

**Comment by jonasbleyl** [comment]
Ah, no worries. Good to hear you found a solution to what you needed anyway :)

Thanks! Good luck with yours as well.
