### ISSUE TITLE
The Values tag cannot be edited

### ISSUE THREAD

**Issue by JunWang002** [BT-OpenSource/bt-grafana-status-dot#11]
The version of grafana is 6.1.6.1, the status bot plugins is version 0.2.3, and the value tag cannot be edited. How should I solve this problem?
![grafana_status_bot_error](https://user-images.githubusercontent.com/44045560/57495928-fc356f80-7302-11e9-825e-d2638dc607b4.png)

**Comment by jonasbleyl** [comment]
It seems like plugins are not allowed to have tabs called "Values" anymore for some reason which is causing this to break. I'll get that changed and submit a new version to Grafana. I'll let you know once it's available for download.

**Comment by jonasbleyl** [comment]
New version has now been released:
https://grafana.com/plugins/btplc-status-dot-panel/installation?version=0.2.4
