### ISSUE TITLE
Special dot color when NoData

### ISSUE THREAD

**Issue by invin12** [BT-OpenSource/bt-grafana-status-dot#5]
Is it possible to define that NoData on my serie now?
Status dot is simply hidden in that case. I think that it is not good, because I cant see a problem.
Maybe some mathjs expression, that will return "0" or any value when Nodata, so I can color it that a problem?

**Comment by jonasbleyl** [comment]
Hi.

You should be able to change the default colour in the options menu which will be used when the data for the series is null. I'd need a more specific example to help with this further though.

Does this help?

**Comment by jonasbleyl** [comment]
Closing due to no response. Let us know if you have any other issues.
