### ISSUE TITLE
Status Dot Panel Issue & Value Mapping Issue

### ISSUE THREAD

**Issue by PanfengFrank** [BT-OpenSource/bt-grafana-status-dot#6]
Hello there! I have a problem with converting “string” to “data” on the graph with Status Dot Panel(Zabbix Datasource). As we can see on the bottom of the image, it indeed shows “up”, but I don’t understand when it calls mathjs, the result still shows “NaN” not “UP”, what I want to display is using a mapping to convert the string “UP” to data “1”, “DOWN” to “0”. How can I make it? I will be greatly appreciate for the timely help. Thanks again.

**Comment by jonasbleyl** [comment]
Hi,
It would seem that the string to number conversion is not possible using mathjs. You're going to need them to be numerical as this plugin currently doesn't provide any mappings for values. Sorry about that!
