### ISSUE TITLE
Dots disappearing

### ISSUE THREAD

**Issue by thehorseman1976** [BT-OpenSource/bt-grafana-status-dot#8]
I have successfully created  a panel using the plugin with several dots, each representing metrics from different hosts and host groups from a Zabbix data source.  Everything was working fine until I started configuring the Links tab for the panel, when for no apparent reason all the "dots" vanished and I can't seem to get them to appear again for those same metrics.  I can create new panels with new metrics for other hosts and and host groups but they also disappear.  

Any ideas?

**Comment by jonasbleyl** [comment]
Hi @thehorseman1976,
Did you modify the contents of the Scratch Pad in the plugin's "Values" tab?
Also, what data does the Debugger show in that tab?

**Comment by thehorseman1976** [comment]
Hello Jonas.

No I did not modify anything in the scratch pad and as soon as I went into the query inspector the dots disappear and this is what I see:

xhrStatus:"complete"
request:Object
method:"POST"
url:"api/datasources/proxy/1"
data:Object
jsonrpc:"2.0"
method:"history.get"
params:Object
output:"extend"
history:"3"
itemids:Array[1]
0:"192376"
sortfield:"clock"
sortorder:"ASC"
time_from:1529341026
time_till:1529344626
id:1
auth:"81c1fe9607d6da26287a80989ff792f8"
response:Object
jsonrpc:"2.0"
result:Array[0]
id:1


-----
With that said I have to be honest with you and share my suspicion that this has to do with Zabbix and not your plugin.  I switch to a different Item on the Metric in question and the dot re-appeared, but as soon as I go back to the item I need to monitor it vanishes again.  I went into Zabbix and noticed there was something odd about the way the Update Intervals were set up and compared it to items that did work and saw a difference.  Unfortunately I don't have the authority to tweak the Zabbix config as it's in another division.

The item in question is a status of a printer being monitored by SNMP and the item in Zabbix is configured with 0 for all intervals which, from what I've read, leads to some weird behavior.  This would explain why after several hours the dot reappears and then later disappears again.

If you concur with me on this then I think you might want to close this bug as it's likely not something on your plugin's end.

**Comment by jonasbleyl** [comment]
I haven't used Zabbix before so I'm not sure what kind of behaviour could be causing that. Though seeing as though it works for other metrics; it does suspiciously sound like it would be an issue with the data source. I can't think of what would be causing this from the plugin's side either.

I'll close this issue for now then.
